run:
  skip-dirs:
    - benchmarks

linters:
  disable-all: true
  enable:
    - deadcode
    - dupl
    - errcheck
    - exportloopref
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - govet
    - ineffassign
    - lll
    - misspell
    - prealloc
    - revive
    - typecheck
    - unconvert
    - varcheck

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - errcheck
